name: Kotlin Ktlint Check and Build

on:
  pull_request:
    branches: [main]

jobs:
  ktlint_job:
    runs-on: ubuntu-latest
    name: Ktlint Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.50.0/ktlint &&
          chmod a+x ktlint
      - name: Run Ktlint
        run: |
          ./ktlint --reporter=checkstyle,output=build/reports/ktlint/ktlint-report.xml
        continue-on-error: true
      - name: Upload Ktlint Report
        uses: actions/upload-artifact@v3
        with:
          name: ktlint-report
          path: build/reports/ktlint/ktlint-report.xml

  build_job:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Add permission for Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
